# Generated by Django 6.0.5 on 2026-06-20 14:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Medicine name (e.g., Paracetamol 500mg)', max_length=255)),
                ('generic_name', models.CharField(blank=True, help_text='Generic name (e.g., Paracetamol)', max_length=255, null=True)),
                ('composition', models.TextField(blank=True, help_text='Active ingredients and their quantities', null=True)),
                ('side_effects', models.TextField(blank=True, help_text='Known side effects', null=True)),
                ('manufacturer', models.CharField(blank=True, help_text='Pharmaceutical company', max_length=255, null=True)),
                ('medicine_type', models.CharField(blank=True, help_text='Tablet, Capsule, Syrup, Injection, etc.', max_length=100, null=True)),
                ('requires_prescription', models.BooleanField(default=False, help_text="Does this require a doctor's prescription?")),
                ('photo', models.ImageField(blank=True, help_text='Medicine photo', null=True, upload_to='medicines/')),
                ('is_approved', models.BooleanField(default=False, help_text='Has an admin approved this medicine for public view?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Medicines',
                'db_table': 'global_catalog',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'generic_name'], name='global_cata_name_17b165_idx')],
            },
        ),
    ]
