# Generated by Django 6.0.5 on 2026-06-20 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('pharmacies', '0002_alter_localinventory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('composition', models.TextField(blank=True)),
                ('side_effects', models.TextField(blank=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('requires_prescription', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='medicines/')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='medicine',
            name='global_cata_name_17b165_idx',
        ),
        migrations.AddField(
            model_name='globalmedicine',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalmedicine',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_medicines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Medicine',
        ),
    ]
