# Generated by Django 6.0.5 on 2026-06-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localinventory',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='localinventory',
            name='local_inven_pharmac_765d38_idx',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='inventory_item',
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='patient',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='pharmacy',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='sale',
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='staffattendance',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='localinventory',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='localinventory',
            name='pharmacy',
        ),
        migrations.DeleteModel(
            name='LowStockNotification',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleItem',
        ),
        migrations.DeleteModel(
            name='StaffAttendance',
        ),
        migrations.DeleteModel(
            name='LocalInventory',
        ),
        migrations.DeleteModel(
            name='Pharmacy',
        ),
    ]
