# Generated by Django 6.0.5 on 2026-08-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_globalmedicine_and_more'),
        ('pharmacies', '0003_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localinventory',
            unique_together={('pharmacy', 'medicine', 'batch_number')},
        ),
    ]
