# Generated by Django 6.0.5 on 2026-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0004_alter_localinventory_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='pan_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
